
x-common-variables: &common-variables
  ASPNETCORE_ENVIRONMENT: Development
  OTEL_EXPORTER_OTLP_ENDPOINT: 'http://otel-collector:4317'
  SEQ_ENDPOINT: 'http://seq:5341'
  APPLICATIONINSIGHTS_CONNECTION_STRING: ${APPLICATIONINSIGHTS_CONNECTION_STRING}

services:

## ----------------- Infra
  redis:
    image: redis:latest
    ports:
      - 6380:6379

  mongo:
    image: mongo:6.0.6
    ports:
      - 27017:27017

  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - 9412:9411
    environment:
      JAVA_OPTS: '-Xms1g -Xmx1g -XX:+ExitOnOutOfMemoryError'

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.78.0
    command: ["--config=conf/config.yaml"]
    environment:
      - APPLICATION_INSIGHTS_INSTRUMENTATION_KEY=${APPLICATION_INSIGHTS_INSTRUMENTATION_KEY}
      - APPLICATION_INSIGHTS_INGESTION_ENDPOINT=${APPLICATION_INSIGHTS_INGESTION_ENDPOINT}/v2/track
    volumes:
      - ./docker/otel-collector-config.yaml:/conf/config.yaml
    depends_on:
      zipkin:
        condition: service_started

  seq:
    image: datalust/seq:latest
    ports:
      - 5341:80
    environment:
      - ACCEPT_EULA=Y