apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: recipes
spec:
  type: state.mongodb
  version: v1
  metadata:
  - name: host
    value: mongo:27017
  - name: keyPrefix
    value: "none"
