receivers:
  otlp:
    protocols:
      http:
      grpc:
extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679
processors:
  attributes:
    actions:
      - key: environment
        value: "Docker"
        action: insert
exporters:
  logging:
  #  verbosity: detailed
  azuremonitor:
    endpoint: "https://dc.services.visualstudio.com/v2/track"
    instrumentation_key: $APPLICATION_INSIGHTS_INSTRUMENTATION_KEY
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging, zipkin, azuremonitor]
    metrics:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging]
    logs:
      receivers: [otlp]
      processors: [attributes]
      exporters: [logging]
  
